name: pull_request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      env:
        REPO_NAME: pi_comtest
        # not accepted as the repo contains uppercase letters
        # REPO_NAME: ${{ github.event.repository.name }}
        REPO_BRANCH: ${{ github.head_ref }}
      run: docker build . --file Dockerfile --tag $REPO_NAME:$REPO_BRANCH

    - name: Get the docker image testing material
      run: wget -O test_docker_call.py https://raw.githubusercontent.com/eurobench/docker_test/master/test_docker_call.py

    - name: test the docker image
      env:
        TEST_PLAN: ANALYSIS/OCTAVE/test_data/test_plan.xml
        DOCKER_IMAGE: pi_comtest:${{ github.head_ref }}
        # not accepted as the repo contains uppercase letters
        # DOCKER_IMAGE: ${{ github.event.repository.name }}:${{ github.head_ref }}
      run: python3 test_docker_call.py
